//! Generated by cargo xtask lensfun-import; the accepted offline resource identity.
pub(crate) const RELEASE: &str = "lensfun-0.3.4";
pub(crate) const COMMIT: &str = "101c745e847a5de4a1e569a94368ce2027198598";
pub(crate) const INDEX_SHA256: &str =
    "c85b0547fb6d8c0c716d45191a3f942944928b09d8af7fe58ca403c6765e2d4f";
