//! Scoped permission grants and denials, outside every catalog, in `<config>/modules/grants.json`:
//! a [`JsonDocument`] like the settings file, with its own `format: 1` marker and bound. Nothing
//! here ever holds a secret: a scope names a resource version, or a profile, adapter, origin, data
//! class and asset. See `docs/design/module-capabilities.md#capability-and-consent-contract`.
use super::{
    descriptor::{CapabilityKind, DataClass},
    document::JsonDocument,
};
#[cfg(test)]
use crate::ErrorKind;
use crate::{AssetId, Error, editor::now_ms};
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use serde_json::Value;
use std::path::PathBuf;

/// The only grants file format this build reads or writes.
pub const GRANTS_FORMAT: u32 = 1;
/// Grants and denials together, revoked grants included. A new record beyond this prunes the
/// oldest revoked grant or denial; when every record is a live grant, it evicts the oldest live
/// remote-image grant, and when every record is a live download grant, it is refused.
pub const MAX_GRANT_RECORDS: usize = 1024;
/// The largest grants file, read or written. A record is well under 1 KiB.
pub const MAX_GRANTS_BYTES: u64 = 2 * 1024 * 1024;

pub const GRANTS_FILE: &str = "grants.json";

/// The permission methods.
pub const GRANT: &str = "module.permission.grant";
pub const DENY: &str = "module.permission.deny";
pub const REVOKE: &str = "module.permission.revoke";
pub const LIST: &str = "module.permission.list";

/// The longest revocation reason a client may give, in characters.
pub const MAX_REASON: usize = 256;

/// The capability kind a grant covers, which decides the shape of its scope.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum GrantKind {
    DownloadArtifact,
    RemoteImageRequest,
}

impl GrantKind {
    pub fn of(kind: &CapabilityKind) -> Self {
        match kind {
            CapabilityKind::DownloadArtifact { .. } => Self::DownloadArtifact,
            CapabilityKind::RemoteImageRequest { .. } => Self::RemoteImageRequest,
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Self::DownloadArtifact => "download-artifact",
            Self::RemoteImageRequest => "remote-image-request",
        }
    }
}

/// `download-artifact`: one declared resource version from the origin of its pinned URL.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DownloadScope {
    pub resource: String,
    pub version: String,
    pub origin: String,
}

/// `remote-image-request`: one data class of one asset, sent to one profile's endpoint origin
/// through its adapter.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RemoteScope {
    pub profile_id: String,
    pub adapter: String,
    pub origin: String,
    pub data: DataClass,
    pub asset_id: AssetId,
}

/// An exact grant scope. Matching is equality: nothing widens a scope, so a grant for one
/// resource version or asset never covers another.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GrantScope {
    Download(DownloadScope),
    Remote(RemoteScope),
}

impl GrantScope {
    pub fn kind(&self) -> GrantKind {
        match self {
            Self::Download(_) => GrantKind::DownloadArtifact,
            Self::Remote(_) => GrantKind::RemoteImageRequest,
        }
    }

    /// A client's scope, read strictly as the shape `kind` takes: an unknown or missing field is a
    /// `validation` error naming it.
    pub fn parse(kind: GrantKind, value: &Value) -> Result<Self, Error> {
        fn strict<T: DeserializeOwned>(kind: GrantKind, value: &Value) -> Result<T, Error> {
            serde_json::from_value(value.clone()).map_err(|error| {
                Error::validation(format!("a {} scope is invalid: {error}", kind.name()))
            })
        }
        Ok(match kind {
            GrantKind::DownloadArtifact => Self::Download(strict(kind, value)?),
            GrantKind::RemoteImageRequest => Self::Remote(strict(kind, value)?),
        })
    }
}

/// Why and when a grant stopped applying.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Revocation {
    pub ms: i64,
    pub reason: String,
}

/// One grant. A revoked grant is kept, with its revocation, until it is pruned.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Grant {
    /// `grant-<uuid>`, generated by the host.
    pub grant_id: String,
    pub module_id: String,
    /// The declared capability's identity.
    pub capability: String,
    pub kind: GrantKind,
    pub scope: GrantScope,
    /// The actor of the request that granted it.
    pub actor: String,
    /// The grant request's identity, kept as its provenance.
    pub request_id: String,
    pub created_ms: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked: Option<Revocation>,
}

impl Grant {
    pub fn is_live(&self) -> bool {
        self.revoked.is_none()
    }

    fn covers(&self, module_id: &str, capability: &str, scope: &GrantScope) -> bool {
        self.module_id == module_id && self.capability == capability && &self.scope == scope
    }
}

/// A recorded "Don't allow" for one exact scope. A later consent request for that scope reports
/// `denied: true`; a grant of the scope clears it.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Denial {
    pub module_id: String,
    pub capability: String,
    pub kind: GrantKind,
    pub scope: GrantScope,
    pub actor: String,
    pub ms: i64,
}

impl Denial {
    fn covers(&self, module_id: &str, capability: &str, scope: &GrantScope) -> bool {
        self.module_id == module_id && self.capability == capability && &self.scope == scope
    }
}

/// `module.permission.list`: grants, revoked ones included, and denials.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrantList {
    pub grants: Vec<Grant>,
    pub denials: Vec<Denial>,
}

/// `module.status`'s `permissions`: how many of a module's grants are live and revoked, and how
/// many denials are recorded. It does not grow with the records, which are read through
/// `module.permission.list`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct PermissionCounts {
    pub live: usize,
    pub revoked: usize,
    pub denials: usize,
}

/// `{format: 1, grants: [...], denials: [...]}`.
#[derive(Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Document {
    #[serde(default)]
    grants: Vec<Grant>,
    #[serde(default)]
    denials: Vec<Denial>,
}

impl Document {
    fn records(&self) -> usize {
        self.grants.len() + self.denials.len()
    }

    /// What the shape cannot say: every record's scope is of its kind, and the records are
    /// within their bound.
    fn check(&self) -> Result<(), String> {
        let mismatched = self
            .grants
            .iter()
            .map(|grant| (grant.kind, grant.scope.kind()))
            .chain(
                self.denials
                    .iter()
                    .map(|denial| (denial.kind, denial.scope.kind())),
            )
            .any(|(kind, scope)| kind != scope);
        if mismatched {
            return Err("a record's scope does not match its kind".into());
        }
        if self.records() > MAX_GRANT_RECORDS {
            return Err(format!("it holds more than {MAX_GRANT_RECORDS} records"));
        }
        Ok(())
    }

    /// Make room for one more record by removing the oldest revoked grant or denial, by the time it
    /// stopped applying. When every record is a live grant, the oldest live `remote-image-request`
    /// grant is evicted, so its scope is asked for again; a `download-artifact` grant is never
    /// evicted, and a file of live download grants alone refuses.
    fn make_room(&mut self) -> Result<(), Error> {
        if self.records() < MAX_GRANT_RECORDS {
            return Ok(());
        }
        let revoked = self
            .grants
            .iter()
            .enumerate()
            .filter_map(|(index, grant)| grant.revoked.as_ref().map(|at| (at.ms, index)))
            .min();
        let denied = self
            .denials
            .iter()
            .enumerate()
            .map(|(index, denial)| (denial.ms, index))
            .min();
        match (revoked, denied) {
            (Some(grant), Some(denial)) if grant <= denial => {
                self.grants.remove(grant.1);
            }
            (_, Some(denial)) => {
                self.denials.remove(denial.1);
            }
            (Some(grant), None) => {
                self.grants.remove(grant.1);
            }
            (None, None) => {
                let remote = self
                    .grants
                    .iter()
                    .enumerate()
                    .filter(|(_, grant)| grant.kind == GrantKind::RemoteImageRequest)
                    .map(|(index, grant)| (grant.created_ms, index))
                    .min()
                    .ok_or_else(|| {
                        Error::resource_limit(format!(
                            "{MAX_GRANT_RECORDS} live grants are recorded; revoke one before granting another"
                        ))
                    })?;
                self.grants.remove(remote.1);
            }
        }
        Ok(())
    }
}

/// What a grant request did: a new grant, or the live grant that already covers the scope. A retry
/// of the request never reaches the store: the owner's request table answers it.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct GrantOutcome {
    pub grant: Grant,
    /// `committed` when anything was written, `no-op` when the scope was already granted.
    pub outcome: super::settings::WriteOutcome,
}

/// The fields of a new grant a caller supplies; the host adds the identity and the time.
pub(crate) struct NewGrant<'a> {
    pub module_id: &'a str,
    pub capability: &'a str,
    pub scope: GrantScope,
    pub actor: &'a str,
    pub request_id: &'a str,
}

/// The grants file of one user, in one directory. Holds no state of its own: every call reads the
/// file again.
#[derive(Clone, Debug)]
pub struct GrantsStore {
    document: JsonDocument<Document>,
}

impl GrantsStore {
    /// A store over `<dir>/grants.json`. Nothing is created until the first write.
    pub fn new(dir: impl Into<PathBuf>) -> Self {
        Self {
            document: JsonDocument::new(dir, GRANTS_FILE, MAX_GRANTS_BYTES, GRANTS_FORMAT)
                .checked(Document::check),
        }
    }

    fn load(&self) -> Result<Document, Error> {
        Ok(self.document.read()?.unwrap_or_default())
    }

    /// Every grant and denial, optionally of one module.
    pub fn list(&self, module_id: Option<&str>) -> Result<GrantList, Error> {
        let document = self.load()?;
        let wanted = |id: &str| module_id.is_none_or(|module_id| module_id == id);
        Ok(GrantList {
            grants: document
                .grants
                .into_iter()
                .filter(|grant| wanted(&grant.module_id))
                .collect(),
            denials: document
                .denials
                .into_iter()
                .filter(|denial| wanted(&denial.module_id))
                .collect(),
        })
    }

    /// How many of one module's grants are live and revoked, and how many denials it has.
    pub fn counts(&self, module_id: &str) -> Result<PermissionCounts, Error> {
        let document = self.load()?;
        let mut counts = PermissionCounts::default();
        for grant in document
            .grants
            .iter()
            .filter(|grant| grant.module_id == module_id)
        {
            if grant.is_live() {
                counts.live += 1;
            } else {
                counts.revoked += 1;
            }
        }
        counts.denials = document
            .denials
            .iter()
            .filter(|denial| denial.module_id == module_id)
            .count();
        Ok(counts)
    }

    /// The live grant covering exactly this scope, and whether a denial of it is recorded.
    pub fn consent(
        &self,
        module_id: &str,
        capability: &str,
        scope: &GrantScope,
    ) -> Result<(Option<Grant>, bool), Error> {
        let document = self.load()?;
        let grant = document
            .grants
            .into_iter()
            .find(|grant| grant.is_live() && grant.covers(module_id, capability, scope));
        let denied = document
            .denials
            .iter()
            .any(|denial| denial.covers(module_id, capability, scope));
        Ok((grant, denied))
    }

    /// Record a grant. A live grant of the same scope is returned instead of a duplicate. A matching
    /// denial is cleared either way. The request identity is kept on the grant as its provenance.
    pub(crate) fn grant(&self, request: NewGrant<'_>) -> Result<GrantOutcome, Error> {
        let NewGrant {
            module_id,
            capability,
            scope,
            actor,
            request_id,
        } = request;
        self.document.transact(|document| {
            let denials = document.denials.len();
            document
                .denials
                .retain(|denial| !denial.covers(module_id, capability, &scope));
            let cleared = document.denials.len() != denials;
            if let Some(live) = document
                .grants
                .iter()
                .find(|grant| grant.is_live() && grant.covers(module_id, capability, &scope))
                .cloned()
            {
                return Ok(GrantOutcome {
                    grant: live,
                    outcome: if cleared {
                        super::settings::WriteOutcome::Committed
                    } else {
                        super::settings::WriteOutcome::NoOp
                    },
                });
            }
            document.make_room()?;
            let grant = Grant {
                grant_id: format!("grant-{}", uuid::Uuid::new_v4().simple()),
                module_id: module_id.to_owned(),
                capability: capability.to_owned(),
                kind: scope.kind(),
                scope,
                actor: actor.to_owned(),
                request_id: request_id.to_owned(),
                created_ms: now_ms(),
                revoked: None,
            };
            document.grants.push(grant.clone());
            Ok(GrantOutcome {
                grant,
                outcome: super::settings::WriteOutcome::Committed,
            })
        })
    }

    /// Record a denial of one exact scope, or refresh the one already recorded.
    pub(crate) fn deny(
        &self,
        module_id: &str,
        capability: &str,
        scope: GrantScope,
        actor: &str,
    ) -> Result<Denial, Error> {
        self.document.transact(|document| {
            document
                .denials
                .retain(|denial| !denial.covers(module_id, capability, &scope));
            document.make_room()?;
            let denial = Denial {
                module_id: module_id.to_owned(),
                capability: capability.to_owned(),
                kind: scope.kind(),
                scope,
                actor: actor.to_owned(),
                ms: now_ms(),
            };
            document.denials.push(denial.clone());
            Ok(denial)
        })
    }

    /// Revoke one grant. Revoking a revoked grant changes nothing and returns it with `false`.
    pub(crate) fn revoke(&self, grant_id: &str, reason: &str) -> Result<(Grant, bool), Error> {
        self.document.transact(|document| {
            let grant = document
                .grants
                .iter_mut()
                .find(|grant| grant.grant_id == grant_id)
                .ok_or_else(|| Error::validation(format!("unknown grant {grant_id}")))?;
            if !grant.is_live() {
                return Ok((grant.clone(), false));
            }
            grant.revoked = Some(Revocation {
                ms: now_ms(),
                reason: reason.to_owned(),
            });
            Ok((grant.clone(), true))
        })
    }

    /// Revoke every live grant `matches` selects and return them. A file with nothing to revoke is
    /// neither locked nor written, so a settings write on a fresh install creates no grants file.
    pub(crate) fn revoke_matching(
        &self,
        matches: impl Fn(&Grant) -> bool,
        reason: &str,
    ) -> Result<Vec<Grant>, Error> {
        let selected = |document: &Document| {
            document
                .grants
                .iter()
                .any(|grant| grant.is_live() && matches(grant))
        };
        if !selected(&self.load()?) {
            return Ok(Vec::new());
        }
        self.document.transact(|document| {
            let ms = now_ms();
            let mut revoked = Vec::new();
            for grant in &mut document.grants {
                if grant.is_live() && matches(grant) {
                    grant.revoked = Some(Revocation {
                        ms,
                        reason: reason.to_owned(),
                    });
                    revoked.push(grant.clone());
                }
            }
            Ok(revoked)
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::capabilities::testing::{MODULE, temp};
    use serde_json::json;
    use std::fs;

    struct Fixture {
        root: PathBuf,
        store: GrantsStore,
    }

    impl Fixture {
        fn new(name: &str) -> Self {
            let root = temp(name);
            Self {
                store: GrantsStore::new(root.join("modules")),
                root,
            }
        }

        fn file(&self) -> PathBuf {
            self.root.join("modules").join(GRANTS_FILE)
        }
    }

    impl Drop for Fixture {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.root);
        }
    }

    fn download_scope(resource: &str) -> GrantScope {
        GrantScope::Download(DownloadScope {
            resource: resource.into(),
            version: "1".into(),
            origin: "https://example.com".into(),
        })
    }

    fn new_grant<'a>(scope: GrantScope, request_id: &'a str) -> NewGrant<'a> {
        NewGrant {
            module_id: MODULE,
            capability: "download",
            scope,
            actor: "permissions",
            request_id,
        }
    }

    #[test]
    fn scopes_parse_strictly_as_their_kind() {
        let download = GrantScope::parse(
            GrantKind::DownloadArtifact,
            &json!({"resource": "palette", "version": "1", "origin": "https://example.com"}),
        )
        .unwrap();
        assert_eq!(download.kind(), GrantKind::DownloadArtifact);
        for (kind, value, expected) in [
            (
                GrantKind::DownloadArtifact,
                json!({"resource": "palette", "extra": 1}),
                "unknown field `extra`",
            ),
            (
                GrantKind::DownloadArtifact,
                json!({"path": "/a"}),
                "a download-artifact scope is invalid",
            ),
            (
                GrantKind::RemoteImageRequest,
                json!({"profile_id": "p", "adapter": "a", "origin": "https://x", "data": "sample-grid-8", "asset_id": "nope"}),
                "invalid AssetId",
            ),
        ] {
            let error = GrantScope::parse(kind, &value).unwrap_err();
            assert_eq!(error.kind, ErrorKind::Validation);
            assert!(error.detail.contains(expected), "{}", error.detail);
        }
    }

    #[test]
    fn a_live_grant_answers_a_second_grant_and_a_denial_is_cleared_by_a_grant() {
        let fixture = Fixture::new("grants-live");
        assert_eq!(fixture.store.list(None).unwrap(), GrantList::default());
        assert!(!fixture.file().exists(), "reading creates nothing");
        let denial = fixture
            .store
            .deny(MODULE, "download", download_scope("/a"), "edit")
            .unwrap();
        assert_eq!(denial.kind, GrantKind::DownloadArtifact);
        assert_eq!(
            fixture
                .store
                .consent(MODULE, "download", &download_scope("/a"))
                .unwrap(),
            (None, true)
        );
        let first = fixture
            .store
            .grant(new_grant(download_scope("/a"), "grant-1"))
            .unwrap();
        assert_eq!(
            first.outcome,
            super::super::settings::WriteOutcome::Committed
        );
        assert!(first.grant.grant_id.starts_with("grant-"));
        assert_eq!(first.grant.actor, "permissions");
        assert_eq!(first.grant.request_id, "grant-1", "kept as provenance");
        let (live, denied) = fixture
            .store
            .consent(MODULE, "download", &download_scope("/a"))
            .unwrap();
        assert_eq!(live.as_ref(), Some(&first.grant));
        assert!(!denied, "the grant cleared the denial");
        // Another request for a scope already granted returns the live grant instead of a copy.
        let again = fixture
            .store
            .grant(new_grant(download_scope("/a"), "grant-2"))
            .unwrap();
        assert_eq!(again.outcome, super::super::settings::WriteOutcome::NoOp);
        assert_eq!(again.grant, first.grant);
        let (revoked, changed) = fixture
            .store
            .revoke(&first.grant.grant_id, "revoked by test")
            .unwrap();
        assert!(changed);
        assert_eq!(revoked.revoked.as_ref().unwrap().reason, "revoked by test");
        assert!(
            !fixture
                .store
                .revoke(&first.grant.grant_id, "again")
                .unwrap()
                .1
        );
        // A revoked grant covers nothing, so granting the scope again records a new grant.
        let renewed = fixture
            .store
            .grant(new_grant(download_scope("/a"), "grant-3"))
            .unwrap();
        assert_eq!(
            renewed.outcome,
            super::super::settings::WriteOutcome::Committed
        );
        assert_ne!(renewed.grant.grant_id, first.grant.grant_id);
        let listed = fixture.store.list(Some(MODULE)).unwrap();
        assert_eq!(listed.grants.len(), 2);
        assert!(
            fixture
                .store
                .list(Some("test.other"))
                .unwrap()
                .grants
                .is_empty()
        );
    }

    #[test]
    fn records_are_bounded_and_the_oldest_revoked_or_denied_is_pruned_first() {
        let fixture = Fixture::new("grants-bounds");
        let mut document = Document::default();
        let live = |index: usize| Grant {
            grant_id: format!("grant-{index}"),
            module_id: MODULE.into(),
            capability: "download".into(),
            kind: GrantKind::DownloadArtifact,
            scope: download_scope(&format!("/{index}")),
            actor: "permissions".into(),
            request_id: format!("request-{index}"),
            created_ms: 1,
            revoked: None,
        };
        document.grants = (0..MAX_GRANT_RECORDS).map(live).collect();
        fs::create_dir_all(fixture.root.join("modules")).unwrap();
        fixture.store.document.write(&document).unwrap();
        let full = fs::read(fixture.file()).unwrap();
        // A file of live download grants has no remote-image grant to evict: it refuses.
        let error = fixture
            .store
            .grant(new_grant(download_scope("/new"), "new"))
            .unwrap_err();
        assert_eq!(error.kind, ErrorKind::ResourceLimit);
        assert_eq!(
            error.detail,
            format!(
                "{MAX_GRANT_RECORDS} live grants are recorded; revoke one before granting another"
            )
        );
        assert_eq!(
            fs::read(fixture.file()).unwrap(),
            full,
            "nothing was written"
        );
        let error = fixture
            .store
            .deny(MODULE, "download", download_scope("/new"), "edit")
            .unwrap_err();
        assert_eq!(
            error.kind,
            ErrorKind::ResourceLimit,
            "a denial is a record too"
        );
        // Two revoked grants: the one revoked first goes first.
        document.grants[10].revoked = Some(Revocation {
            ms: 20,
            reason: "later".into(),
        });
        document.grants[20].revoked = Some(Revocation {
            ms: 10,
            reason: "earlier".into(),
        });
        fixture.store.document.write(&document).unwrap();
        fixture
            .store
            .grant(new_grant(download_scope("/new"), "new"))
            .unwrap();
        let grants = fixture.store.list(None).unwrap().grants;
        assert_eq!(grants.len(), MAX_GRANT_RECORDS);
        assert!(grants.iter().all(|grant| grant.grant_id != "grant-20"));
        assert!(grants.iter().any(|grant| grant.grant_id == "grant-10"));
    }

    #[test]
    fn at_the_bound_the_oldest_live_remote_grant_is_evicted_and_never_a_download() {
        let fixture = Fixture::new("grants-evict");
        let half = MAX_GRANT_RECORDS / 2;
        // The download grants are the oldest records, so age alone would take one of them.
        let download = |index: usize| Grant {
            grant_id: format!("download-{index}"),
            module_id: MODULE.into(),
            capability: "download".into(),
            kind: GrantKind::DownloadArtifact,
            scope: download_scope(&format!("/{index}")),
            actor: "permissions".into(),
            request_id: format!("download-request-{index}"),
            created_ms: index as i64,
            revoked: None,
        };
        let remote_scope = || {
            GrantScope::Remote(RemoteScope {
                profile_id: "profile".into(),
                adapter: "adapter".into(),
                origin: "https://example.com".into(),
                data: DataClass::SampleGrid8,
                asset_id: AssetId::new(),
            })
        };
        // The remote grants are listed newest first, so the oldest is the last one listed.
        let remote = |index: usize| Grant {
            grant_id: format!("remote-{index}"),
            module_id: MODULE.into(),
            capability: "send".into(),
            kind: GrantKind::RemoteImageRequest,
            scope: remote_scope(),
            actor: "permissions".into(),
            request_id: format!("remote-request-{index}"),
            created_ms: 10_000 - index as i64,
            revoked: None,
        };
        let document = Document {
            grants: (0..half)
                .map(download)
                .chain((0..MAX_GRANT_RECORDS - half).map(remote))
                .collect(),
            denials: Vec::new(),
        };
        let downloads: Vec<Grant> = document.grants[..half].to_vec();
        fs::create_dir_all(fixture.root.join("modules")).unwrap();
        fixture.store.document.write(&document).unwrap();
        let oldest = format!("remote-{}", MAX_GRANT_RECORDS - half - 1);
        let next = format!("remote-{}", MAX_GRANT_RECORDS - half - 2);
        let granted = fixture
            .store
            .grant(NewGrant {
                capability: "send",
                ..new_grant(remote_scope(), "new-remote")
            })
            .unwrap();
        let grants = fixture.store.list(None).unwrap().grants;
        assert_eq!(grants.len(), MAX_GRANT_RECORDS);
        assert!(grants.iter().all(|grant| grant.grant_id != oldest));
        assert!(grants.iter().any(|grant| grant.grant_id == next));
        assert!(grants.contains(&granted.grant));
        assert_eq!(
            grants
                .iter()
                .filter(|grant| grant.kind == GrantKind::DownloadArtifact)
                .cloned()
                .collect::<Vec<_>>(),
            downloads,
            "every download grant is untouched"
        );
        // A new download grant takes the next oldest remote grant's place, not a download's.
        fixture
            .store
            .grant(new_grant(download_scope("/new"), "new-download"))
            .unwrap();
        let grants = fixture.store.list(None).unwrap().grants;
        assert_eq!(grants.len(), MAX_GRANT_RECORDS);
        assert!(grants.iter().all(|grant| grant.grant_id != next));
        assert_eq!(
            grants
                .iter()
                .filter(|grant| grant.kind == GrantKind::DownloadArtifact)
                .count(),
            half + 1
        );
        // The evicted scope is asked for again: it has no live grant and no denial.
        let evicted = document
            .grants
            .iter()
            .find(|grant| grant.grant_id == oldest)
            .unwrap();
        assert_eq!(
            fixture
                .store
                .consent(MODULE, "send", &evicted.scope)
                .unwrap(),
            (None, false)
        );
    }

    #[test]
    fn another_format_or_shape_is_refused_and_kept_unchanged() {
        let fixture = Fixture::new("grants-format");
        fs::create_dir_all(fixture.root.join("modules")).unwrap();
        for (name, contents) in [
            (
                "format",
                json!({"format": 2, "grants": [], "denials": []}).to_string(),
            ),
            ("marker", json!({"grants": []}).to_string()),
            ("json", "{not json".to_owned()),
            (
                "shape",
                json!({"format": 1, "grants": [], "denials": [], "extra": true}).to_string(),
            ),
            (
                "kind",
                json!({"format": 1, "grants": [], "denials": [{
                    "module_id": MODULE, "capability": "download", "kind": "download-artifact",
                    "scope": {"path": "/a"}, "actor": "edit", "ms": 1,
                }]})
                .to_string(),
            ),
        ] {
            fs::write(fixture.file(), &contents).unwrap();
            let error = fixture.store.list(None).unwrap_err();
            assert_eq!(
                error.kind,
                ErrorKind::Incompatible,
                "{name}: {}",
                error.detail
            );
            let error = fixture
                .store
                .grant(new_grant(download_scope("/a"), "a"))
                .unwrap_err();
            assert_eq!(error.kind, ErrorKind::Incompatible, "{name}");
            let error = fixture
                .store
                .revoke_matching(|_| true, "reset")
                .unwrap_err();
            assert_eq!(error.kind, ErrorKind::Incompatible, "{name}");
            assert_eq!(
                fs::read_to_string(fixture.file()).unwrap(),
                contents,
                "{name}"
            );
        }
    }

    #[test]
    fn revoking_nothing_creates_no_file() {
        let fixture = Fixture::new("grants-revoke-nothing");
        assert!(
            fixture
                .store
                .revoke_matching(|_| true, "reset")
                .unwrap()
                .is_empty()
        );
        assert!(!fixture.root.exists(), "nothing was created");
        fixture
            .store
            .grant(new_grant(download_scope("/a"), "a"))
            .unwrap();
        let revoked = fixture
            .store
            .revoke_matching(|grant| grant.capability == "download", "selection changed")
            .unwrap();
        assert_eq!(revoked.len(), 1);
        assert_eq!(
            revoked[0].revoked.as_ref().unwrap().reason,
            "selection changed"
        );
    }
}
